version: '3.5'

services:

  django:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    image: blog_django
    depends_on:
        - db
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.prod/.postgres
    volumes:
      - ./docker_logs/django_logs:/app/logs
      - ./media/media:/app/media/media
  next:
    build:
      context: .
      dockerfile: compose/next/Dockerfile
    image: blog_next
    restart: always
    depends_on:
        - django
    ports:
        - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    image: blog_nginx
    restart: always
    ports:
      - "1080:80"
      - "1443:443"
    depends_on:
      - next
      - django
    volumes:
      - ./media/media:/srv/static/media
      - ./docker_logs/nginx_logs:/var/log/nginx
  db:
    hostname: db
    image: kartoza/postgis
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - ./.envs/.prod/.postgres
