# Generated by Django 3.2 on 2021-06-24 15:30

from django.db import migrations, models
import django.utils.timezone
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=256, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Python')])),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content', martor.models.MartorField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
