# Generated by Django 3.2 on 2021-04-19 15:17

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=124)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('preview', models.ImageField(upload_to='preview/')),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('tags', models.ManyToManyField(related_name='posts', to='post.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
