# Generated by Django 3.2 on 2021-06-23 07:05

import colorfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='font_color',
            field=colorfield.fields.ColorField(default='#030000', max_length=18),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='views',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
