# Generated by Django 3.2 on 2021-06-23 07:27

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210623_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hover_color',
            field=colorfield.fields.ColorField(default='#d1a1a1', max_length=18),
        ),
    ]
