# Generated by Django 3.2 on 2021-06-23 15:01

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=martor.models.MartorField(default=''),
            preserve_default=False,
        ),
    ]
