# Generated by Django 3.2 on 2021-06-17 13:34

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210617_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=martor.models.MartorField(blank=True, default=None, null=True),
        ),
    ]
