# Generated by Django 3.2 on 2021-06-28 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210624_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
