import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Layout, Menu, Breadcrumb } from 'antd';

const { Header, Content, Footer, Sider } = Layout;
const { SubMenu } = Menu;


export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout  theme='light' style={{ height: "100%" }}>
    <Header style={{ position: 'fixed', zIndex: 1, width: '100%', padding: 0, background: 'white'}}>
      <div className="logo" />
      <Menu theme="light" mode="horizontal" defaultSelectedKeys={['2']} style={{display:'flex', justifyContent: 'end'}}>
        <Menu.Item key="1">nav 1</Menu.Item>
      </Menu>
    </Header>



    <Content style={{ padding: '0 50px', backgroundColor: 'white'}}>
      <Breadcrumb style={{ margin: '16px 0' }}>
        <Breadcrumb.Item>Home</Breadcrumb.Item>
        <Breadcrumb.Item>List</Breadcrumb.Item>
        <Breadcrumb.Item>App</Breadcrumb.Item>
      </Breadcrumb>
      <Layout className="site-layout-background" style={{ padding: '24px 0', backgroundColor: 'white' }}>
        <Sider className="site-layout-background" width={200}>
          <Menu
            mode="inline"
            defaultSelectedKeys={['1']}
            defaultOpenKeys={['sub1']}
            style={{ height: '100%' }}
            selectable={false}
          >
            
           <li>
             da
           </li>
           <li>
             5
           </li>

          </Menu>
        </Sider>
        <Content style={{ padding: '0 24px', minHeight: 280, backgroundColor: 'white' }}>Content</Content>
      </Layout>
    </Content>



    <Footer style={{ textAlign: 'center' }}>Ant Design ©2018 Created by Ant UED</Footer>
  </Layout>

    </div>
  )
}
