import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'

export default function Post({post}) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1>Post</h1>
    <h2>{post.title}</h2>
      
      <div dangerouslySetInnerHTML={{ __html: post.content }} />
    </div>
  )
}

export async function getStaticPaths() {

  let response = await axios.get('http://localhost:8000/api/post/')
  let posts = response.data

  const paths = posts.map((post) => ({
    params: { slug: post.slug },
  }))
  return { paths, fallback: false }
}


export async function getStaticProps({ params }) {

  let response = await axios.get(`http://localhost:8000/api/post/${params.slug}/`)
  let post = response.data
  return { props: { post } }
}