import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Button, Space, DatePicker, Card } from 'antd';
import { CiCircleFilled } from '@ant-design/icons';


export default function Blog({posts}) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1>Blog</h1>
    <div style={{ padding: 100 }}>
      <Space direction="vertical">
        <Button type="primary">Primary Button</Button>
        <Button type="ghost">Ghost Button</Button>
        <DatePicker  />
        <CiCircleFilled />
      </Space>
    </div>
    <ul>
      {posts.map((post) => (
        <li><Link href={`/blog/${post.slug}`}><a>{post.title}</a></Link></li>
      ))}
    </ul>

    </div>
  )
}

export async function getStaticProps() {
    // Call an external API endpoint to get posts
    const res = await fetch('http://localhost:8000/api/post/')
    const posts = await res.json()
  
    // By returning { props: { posts } }, the Blog component
    // will receive `posts` as a prop at build time
    return {
      props: {
        posts,
      },
    }
  }
  