# Generated by Django 3.2 on 2021-06-24 15:08

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='content',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
