# Generated by Django 3.2 on 2021-06-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210624_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
